import { Customer } from "@/types/customer.types";

export const emptyCustomer: Partial<Customer> = {
  id: "",
  name: "",
  email: "",
  phone: "",
  unit: "",
  street: "",
  city: "",
  state: "",
  zip: "",
  squareFootage: 0,
  cleaningType: "BASE",
  priceEstimate: 0,
  homeType: "",
  bedrooms: 0,
  bathrooms: 0,
  entryInstructions: "",
  hasPets: false,
  parkingInstructions: "",
  alarmSystemInstructions: "",
  cleaningNotes: "",
  preferredTimeOfDay: "",
  preferredDays: [],
  preferredCleanerId: undefined,
  rotationSystemOptIn: false,
  suppliesProvidedByCustomer: false,
  customerSince: "",
  isVIP: false,
  notes: "",
  referredBy: "",
  organizationId: "",
  createdByUserId: "",
  billingMethod: "",
  invoiceNotes: "",
  isActive: true,
  crmId: "",
  emailOptIn: false,
  createdAt: "",
  updatedAt: "",
};
